version: '2'
services:
  prms:
    build: .
    image: nhdusgs/prms
    hostname: prms
    container_name: prms
    volumes:
     - .:/var/lib/nhm
  ofp:
    build: .
    image: nhdusgs/ofp
    hostname: ofp
    container_name: ofp
    volumes:
     - .:/var/lib/nhm
volumes:
     .:
