version: '2'
services:
  prms:
    build: .
    image: nhmusgs/prms
    hostname: prms
    container_name: prms
  onhm-fetcher-parser:
    build: .
    image: nhmusgs/onhm-fetcher-parser
    hostname: onhm-fetcher-parser
    container_name: onhm-fetcher-parser
