version: '2.3'
services:
  prms:
    build: .
    image: nhdusgs/prms
    hostname: prms
    container_name: prms
    volumes:
     - .:/var/lib/nhm
  onhm-fetcher-parser:
    build: .
    image: nhdusgs/onhm-fetcher-parser
    hostname: onhm-fetcher-parser
    container_name: onhm-fetcher-parser
    volumes:
     - .:/var/lib/nhm
volumes:
     .:
