version: "3.2"
services:
  ofp:
    build: .
    image: nhmusgs/ofp
    hostname: ofp
    container_name: ofp
    environment:
      - days=60
    volumes:
      - nhm:/var/lib/nhm
    entrypoint: /usr/local/bin/ofp-entrypoint
  prms:
    build: .
    image: nhmusgs/prms
    hostname: prms
    container_name: prms
    entrypoint: /usr/local/bin/prms-entrypoint
volumes:
  nhm:
    driver: local
